### ISSUE TITLE
Use relative imports

### ISSUE THREAD

**Issue by agoose77** [sjdv1982/seamless#4]
Currently many imports that access other sub packages are accessing them from the seamless.XXX package. This should be changed to support relative imports

**Comment by sjdv1982** [comment]
I did a search for seamless.XXX, and it shows hits mostly for lib/ and silk/. I am a bit reluctant to make explicit relative imports for those, because maybe those will be eventually be packages of their own

**Comment by sjdv1982** [comment]
A code cleanup / refactor is scheduled for seamless 0.4
