### ISSUE TITLE
Eliminate global state

### ISSUE THREAD

**Issue by agoose77** [sjdv1982/seamless#5]
With the exception of context manager state, we should avoid building in global state at this stage of development

**Comment by sjdv1982** [comment]
I was thinking the same. I am not happy about the syntax of contexts, I think we should have one active context where every cell/process gets added to automatically. 
I see one other need for global state. Inside a macro, cell.fromfile should take the source directory of the macro file as current directory, whereas outside a macro, it should be os.getcwd().  I added a "macro mode" for this.

**Comment by sjdv1982** [comment]
Will be addressed with a state system using composite cells, scheduled for seamless 0.2
